/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrimerRouteImport } from './routes/primer'
import { Route as MovesRouteImport } from './routes/moves'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as MarketRouteImport } from './routes/market'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as AgentNegotiationRouteImport } from './routes/agent-negotiation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ApiPublicPurchaseRouteImport } from './routes/api/public/purchase'
import { Route as ApiPublicPinRouteImport } from './routes/api/public/pin'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicArcRpcRouteImport } from './routes/api/public/arc-rpc'
import { Route as ApiPublicAgentCardRouteImport } from './routes/api/public/agent-card'
import { Route as ApiPublicX402ResourcesRouteImport } from './routes/api/public/x402/resources'
import { Route as ApiPublicUcpSelfTestRouteImport } from './routes/api/public/ucp/self-test'
import { Route as ApiPublicUcpDiscoveryRouteImport } from './routes/api/public/ucp/discovery'
import { Route as ApiPublicErc1271AuthorizerRouteImport } from './routes/api/public/erc1271/authorizer'
import { Route as ApiPublicAp2MandateRouteImport } from './routes/api/public/ap2/mandate'
import { Route as ApiPublicA2aMessageRouteImport } from './routes/api/public/a2a/message'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimerRoute = PrimerRouteImport.update({
  id: '/primer',
  path: '/primer',
  getParentRoute: () => rootRouteImport,
} as any)
const MovesRoute = MovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentNegotiationRoute = AgentNegotiationRouteImport.update({
  id: '/agent-negotiation',
  path: '/agent-negotiation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurchaseRoute = ApiPublicPurchaseRouteImport.update({
  id: '/api/public/purchase',
  path: '/api/public/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPinRoute = ApiPublicPinRouteImport.update({
  id: '/api/public/pin',
  path: '/api/public/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArcRpcRoute = ApiPublicArcRpcRouteImport.update({
  id: '/api/public/arc-rpc',
  path: '/api/public/arc-rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCardRoute = ApiPublicAgentCardRouteImport.update({
  id: '/api/public/agent-card',
  path: '/api/public/agent-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402ResourcesRoute = ApiPublicX402ResourcesRouteImport.update({
  id: '/api/public/x402/resources',
  path: '/api/public/x402/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUcpSelfTestRoute = ApiPublicUcpSelfTestRouteImport.update({
  id: '/api/public/ucp/self-test',
  path: '/api/public/ucp/self-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUcpDiscoveryRoute = ApiPublicUcpDiscoveryRouteImport.update({
  id: '/api/public/ucp/discovery',
  path: '/api/public/ucp/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErc1271AuthorizerRoute =
  ApiPublicErc1271AuthorizerRouteImport.update({
    id: '/api/public/erc1271/authorizer',
    path: '/api/public/erc1271/authorizer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAp2MandateRoute = ApiPublicAp2MandateRouteImport.update({
  id: '/api/public/ap2/mandate',
  path: '/api/public/ap2/mandate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicA2aMessageRoute = ApiPublicA2aMessageRouteImport.update({
  id: '/api/public/a2a/message',
  path: '/api/public/a2a/message',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-negotiation': typeof AgentNegotiationRoute
  '/deck': typeof DeckRoute
  '/market': typeof MarketRoute
  '/markets': typeof MarketsRoute
  '/moves': typeof MovesRoute
  '/primer': typeof PrimerRoute
  '/shop': typeof ShopRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/agent-card': typeof ApiPublicAgentCardRoute
  '/api/public/arc-rpc': typeof ApiPublicArcRpcRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/pin': typeof ApiPublicPinRoute
  '/api/public/purchase': typeof ApiPublicPurchaseRoute
  '/api/public/a2a/message': typeof ApiPublicA2aMessageRoute
  '/api/public/ap2/mandate': typeof ApiPublicAp2MandateRoute
  '/api/public/erc1271/authorizer': typeof ApiPublicErc1271AuthorizerRoute
  '/api/public/ucp/discovery': typeof ApiPublicUcpDiscoveryRoute
  '/api/public/ucp/self-test': typeof ApiPublicUcpSelfTestRoute
  '/api/public/x402/resources': typeof ApiPublicX402ResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-negotiation': typeof AgentNegotiationRoute
  '/deck': typeof DeckRoute
  '/market': typeof MarketRoute
  '/markets': typeof MarketsRoute
  '/moves': typeof MovesRoute
  '/primer': typeof PrimerRoute
  '/shop': typeof ShopRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/agent-card': typeof ApiPublicAgentCardRoute
  '/api/public/arc-rpc': typeof ApiPublicArcRpcRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/pin': typeof ApiPublicPinRoute
  '/api/public/purchase': typeof ApiPublicPurchaseRoute
  '/api/public/a2a/message': typeof ApiPublicA2aMessageRoute
  '/api/public/ap2/mandate': typeof ApiPublicAp2MandateRoute
  '/api/public/erc1271/authorizer': typeof ApiPublicErc1271AuthorizerRoute
  '/api/public/ucp/discovery': typeof ApiPublicUcpDiscoveryRoute
  '/api/public/ucp/self-test': typeof ApiPublicUcpSelfTestRoute
  '/api/public/x402/resources': typeof ApiPublicX402ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-negotiation': typeof AgentNegotiationRoute
  '/deck': typeof DeckRoute
  '/market': typeof MarketRoute
  '/markets': typeof MarketsRoute
  '/moves': typeof MovesRoute
  '/primer': typeof PrimerRoute
  '/shop': typeof ShopRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/agent-card': typeof ApiPublicAgentCardRoute
  '/api/public/arc-rpc': typeof ApiPublicArcRpcRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/pin': typeof ApiPublicPinRoute
  '/api/public/purchase': typeof ApiPublicPurchaseRoute
  '/api/public/a2a/message': typeof ApiPublicA2aMessageRoute
  '/api/public/ap2/mandate': typeof ApiPublicAp2MandateRoute
  '/api/public/erc1271/authorizer': typeof ApiPublicErc1271AuthorizerRoute
  '/api/public/ucp/discovery': typeof ApiPublicUcpDiscoveryRoute
  '/api/public/ucp/self-test': typeof ApiPublicUcpSelfTestRoute
  '/api/public/x402/resources': typeof ApiPublicX402ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-negotiation'
    | '/deck'
    | '/market'
    | '/markets'
    | '/moves'
    | '/primer'
    | '/shop'
    | '/product/$handle'
    | '/api/public/agent-card'
    | '/api/public/arc-rpc'
    | '/api/public/catalog'
    | '/api/public/pin'
    | '/api/public/purchase'
    | '/api/public/a2a/message'
    | '/api/public/ap2/mandate'
    | '/api/public/erc1271/authorizer'
    | '/api/public/ucp/discovery'
    | '/api/public/ucp/self-test'
    | '/api/public/x402/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-negotiation'
    | '/deck'
    | '/market'
    | '/markets'
    | '/moves'
    | '/primer'
    | '/shop'
    | '/product/$handle'
    | '/api/public/agent-card'
    | '/api/public/arc-rpc'
    | '/api/public/catalog'
    | '/api/public/pin'
    | '/api/public/purchase'
    | '/api/public/a2a/message'
    | '/api/public/ap2/mandate'
    | '/api/public/erc1271/authorizer'
    | '/api/public/ucp/discovery'
    | '/api/public/ucp/self-test'
    | '/api/public/x402/resources'
  id:
    | '__root__'
    | '/'
    | '/agent-negotiation'
    | '/deck'
    | '/market'
    | '/markets'
    | '/moves'
    | '/primer'
    | '/shop'
    | '/product/$handle'
    | '/api/public/agent-card'
    | '/api/public/arc-rpc'
    | '/api/public/catalog'
    | '/api/public/pin'
    | '/api/public/purchase'
    | '/api/public/a2a/message'
    | '/api/public/ap2/mandate'
    | '/api/public/erc1271/authorizer'
    | '/api/public/ucp/discovery'
    | '/api/public/ucp/self-test'
    | '/api/public/x402/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentNegotiationRoute: typeof AgentNegotiationRoute
  DeckRoute: typeof DeckRoute
  MarketRoute: typeof MarketRoute
  MarketsRoute: typeof MarketsRoute
  MovesRoute: typeof MovesRoute
  PrimerRoute: typeof PrimerRoute
  ShopRoute: typeof ShopRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ApiPublicAgentCardRoute: typeof ApiPublicAgentCardRoute
  ApiPublicArcRpcRoute: typeof ApiPublicArcRpcRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicPinRoute: typeof ApiPublicPinRoute
  ApiPublicPurchaseRoute: typeof ApiPublicPurchaseRoute
  ApiPublicA2aMessageRoute: typeof ApiPublicA2aMessageRoute
  ApiPublicAp2MandateRoute: typeof ApiPublicAp2MandateRoute
  ApiPublicErc1271AuthorizerRoute: typeof ApiPublicErc1271AuthorizerRoute
  ApiPublicUcpDiscoveryRoute: typeof ApiPublicUcpDiscoveryRoute
  ApiPublicUcpSelfTestRoute: typeof ApiPublicUcpSelfTestRoute
  ApiPublicX402ResourcesRoute: typeof ApiPublicX402ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primer': {
      id: '/primer'
      path: '/primer'
      fullPath: '/primer'
      preLoaderRoute: typeof PrimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moves': {
      id: '/moves'
      path: '/moves'
      fullPath: '/moves'
      preLoaderRoute: typeof MovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-negotiation': {
      id: '/agent-negotiation'
      path: '/agent-negotiation'
      fullPath: '/agent-negotiation'
      preLoaderRoute: typeof AgentNegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purchase': {
      id: '/api/public/purchase'
      path: '/api/public/purchase'
      fullPath: '/api/public/purchase'
      preLoaderRoute: typeof ApiPublicPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pin': {
      id: '/api/public/pin'
      path: '/api/public/pin'
      fullPath: '/api/public/pin'
      preLoaderRoute: typeof ApiPublicPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/arc-rpc': {
      id: '/api/public/arc-rpc'
      path: '/api/public/arc-rpc'
      fullPath: '/api/public/arc-rpc'
      preLoaderRoute: typeof ApiPublicArcRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-card': {
      id: '/api/public/agent-card'
      path: '/api/public/agent-card'
      fullPath: '/api/public/agent-card'
      preLoaderRoute: typeof ApiPublicAgentCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/resources': {
      id: '/api/public/x402/resources'
      path: '/api/public/x402/resources'
      fullPath: '/api/public/x402/resources'
      preLoaderRoute: typeof ApiPublicX402ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ucp/self-test': {
      id: '/api/public/ucp/self-test'
      path: '/api/public/ucp/self-test'
      fullPath: '/api/public/ucp/self-test'
      preLoaderRoute: typeof ApiPublicUcpSelfTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ucp/discovery': {
      id: '/api/public/ucp/discovery'
      path: '/api/public/ucp/discovery'
      fullPath: '/api/public/ucp/discovery'
      preLoaderRoute: typeof ApiPublicUcpDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erc1271/authorizer': {
      id: '/api/public/erc1271/authorizer'
      path: '/api/public/erc1271/authorizer'
      fullPath: '/api/public/erc1271/authorizer'
      preLoaderRoute: typeof ApiPublicErc1271AuthorizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ap2/mandate': {
      id: '/api/public/ap2/mandate'
      path: '/api/public/ap2/mandate'
      fullPath: '/api/public/ap2/mandate'
      preLoaderRoute: typeof ApiPublicAp2MandateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/a2a/message': {
      id: '/api/public/a2a/message'
      path: '/api/public/a2a/message'
      fullPath: '/api/public/a2a/message'
      preLoaderRoute: typeof ApiPublicA2aMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentNegotiationRoute: AgentNegotiationRoute,
  DeckRoute: DeckRoute,
  MarketRoute: MarketRoute,
  MarketsRoute: MarketsRoute,
  MovesRoute: MovesRoute,
  PrimerRoute: PrimerRoute,
  ShopRoute: ShopRoute,
  ProductHandleRoute: ProductHandleRoute,
  ApiPublicAgentCardRoute: ApiPublicAgentCardRoute,
  ApiPublicArcRpcRoute: ApiPublicArcRpcRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicPinRoute: ApiPublicPinRoute,
  ApiPublicPurchaseRoute: ApiPublicPurchaseRoute,
  ApiPublicA2aMessageRoute: ApiPublicA2aMessageRoute,
  ApiPublicAp2MandateRoute: ApiPublicAp2MandateRoute,
  ApiPublicErc1271AuthorizerRoute: ApiPublicErc1271AuthorizerRoute,
  ApiPublicUcpDiscoveryRoute: ApiPublicUcpDiscoveryRoute,
  ApiPublicUcpSelfTestRoute: ApiPublicUcpSelfTestRoute,
  ApiPublicX402ResourcesRoute: ApiPublicX402ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
