/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ApiPublicPurchaseRouteImport } from './routes/api/public/purchase'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicAgentCardRouteImport } from './routes/api/public/agent-card'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurchaseRoute = ApiPublicPurchaseRouteImport.update({
  id: '/api/public/purchase',
  path: '/api/public/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCardRoute = ApiPublicAgentCardRouteImport.update({
  id: '/api/public/agent-card',
  path: '/api/public/agent-card',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/markets': typeof MarketsRoute
  '/shop': typeof ShopRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/agent-card': typeof ApiPublicAgentCardRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/purchase': typeof ApiPublicPurchaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/markets': typeof MarketsRoute
  '/shop': typeof ShopRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/agent-card': typeof ApiPublicAgentCardRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/purchase': typeof ApiPublicPurchaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/markets': typeof MarketsRoute
  '/shop': typeof ShopRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/agent-card': typeof ApiPublicAgentCardRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/purchase': typeof ApiPublicPurchaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deck'
    | '/markets'
    | '/shop'
    | '/product/$handle'
    | '/api/public/agent-card'
    | '/api/public/catalog'
    | '/api/public/purchase'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deck'
    | '/markets'
    | '/shop'
    | '/product/$handle'
    | '/api/public/agent-card'
    | '/api/public/catalog'
    | '/api/public/purchase'
  id:
    | '__root__'
    | '/'
    | '/deck'
    | '/markets'
    | '/shop'
    | '/product/$handle'
    | '/api/public/agent-card'
    | '/api/public/catalog'
    | '/api/public/purchase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckRoute: typeof DeckRoute
  MarketsRoute: typeof MarketsRoute
  ShopRoute: typeof ShopRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ApiPublicAgentCardRoute: typeof ApiPublicAgentCardRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicPurchaseRoute: typeof ApiPublicPurchaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purchase': {
      id: '/api/public/purchase'
      path: '/api/public/purchase'
      fullPath: '/api/public/purchase'
      preLoaderRoute: typeof ApiPublicPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-card': {
      id: '/api/public/agent-card'
      path: '/api/public/agent-card'
      fullPath: '/api/public/agent-card'
      preLoaderRoute: typeof ApiPublicAgentCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckRoute: DeckRoute,
  MarketsRoute: MarketsRoute,
  ShopRoute: ShopRoute,
  ProductHandleRoute: ProductHandleRoute,
  ApiPublicAgentCardRoute: ApiPublicAgentCardRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicPurchaseRoute: ApiPublicPurchaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
